version: 0.0
os: linux
files:
  - source: /index.php
    # destination: /var/www/html/index.php
    destination: /usr/share/nginx/html/index.php
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
